/*!
* \file   GeneralizedMaxwell.cxx
* \brief  this file implements the GeneralizedMaxwell Behaviour.
*         File generated by tfel version 3.2.1
* \author BenoÃ®t Bary
* \date   8 / 10 / 2014
 */

#include<string>
#include<cstring>
#include<sstream>
#include<fstream>
#include<stdexcept>

#include"TFEL/Raise.hxx"
#include"TFEL/Material/GeneralizedMaxwellBehaviourData.hxx"
#include"TFEL/Material/GeneralizedMaxwellIntegrationData.hxx"
#include"TFEL/Material/GeneralizedMaxwell.hxx"

namespace tfel{

namespace material{

GeneralizedMaxwellParametersInitializer&
GeneralizedMaxwellParametersInitializer::get()
{
static GeneralizedMaxwellParametersInitializer i;
return i;
}

GeneralizedMaxwellParametersInitializer::GeneralizedMaxwellParametersInitializer()
{
this->minimal_time_step_scaling_factor = 0.1;
this->maximal_time_step_scaling_factor = 1.79769e+308;
// Reading parameters from a file
GeneralizedMaxwellParametersInitializer::readParameters(*this,"GeneralizedMaxwell-parameters.txt");
}

void
GeneralizedMaxwellParametersInitializer::set(const char* const key,
const double v){
using namespace std;
if(::strcmp("minimal_time_step_scaling_factor",key)==0){
this->minimal_time_step_scaling_factor = v;
} else if(::strcmp("maximal_time_step_scaling_factor",key)==0){
this->maximal_time_step_scaling_factor = v;
} else {
tfel::raise("GeneralizedMaxwellParametersInitializer::set: "
" no parameter named '"+std::string(key)+"'");
}
}

double
GeneralizedMaxwellParametersInitializer::getDouble(const std::string& n,
const std::string& v)
{
double value;
std::istringstream converter(v);
converter >> value;
tfel::raise_if(!converter||(!converter.eof()),
"GeneralizedMaxwellParametersInitializer::getDouble: "
"can't convert '"+v+"' to double for parameter '"+ n+"'");
return value;
}

void
GeneralizedMaxwellParametersInitializer::readParameters(GeneralizedMaxwellParametersInitializer& pi,const char* const fn){
auto tokenize = [](const std::string& line){
std::istringstream tokenizer(line);
std::vector<std::string> tokens;
std::copy(std::istream_iterator<std::string>(tokenizer),
std::istream_iterator<std::string>(),
std::back_inserter(tokens));
return tokens;
};
std::ifstream f(fn);
if(!f){
return;
}
size_t ln = 1u;
while(!f.eof()){
auto line = std::string{};
std::getline(f,line);
auto tokens = tokenize(line);
auto throw_if = [ln,line,fn](const bool c,const std::string& m){
tfel::raise_if(c,"GeneralizedMaxwellParametersInitializer::readParameters: "
"error at line '"+std::to_string(ln)+"' "
"while reading parameter file '"+std::string(fn)+"'"
"("+m+")");
};
if(tokens.empty()){
continue;
}
if(tokens[0][0]=='#'){
continue;
}
throw_if(tokens.size()!=2u,"invalid number of tokens");
if("minimal_time_step_scaling_factor"==tokens[0]){
pi.minimal_time_step_scaling_factor = GeneralizedMaxwellParametersInitializer::getDouble(tokens[0],tokens[1]);
} else if("maximal_time_step_scaling_factor"==tokens[0]){
pi.maximal_time_step_scaling_factor = GeneralizedMaxwellParametersInitializer::getDouble(tokens[0],tokens[1]);
} else {
throw_if(true,"invalid parameter '"+tokens[0]+"'");
}
}
}

} // end of namespace material

} // end of namespace tfel

