# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Gui.ui'
#
# Devloped with PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore,QtGui, QtWidgets
from tkinter import filedialog
import numpy as np
import matplotlib.pyplot as plt
from LibraryGUIPostPro.resultExtraction_ref import *
from LibraryGUIPostPro.Contact import *
from math import log10
import LibraryGUIPostPro.CheckableComboBox as Check
from scipy.interpolate import PchipInterpolator
from scipy.signal import savgol_filter
import json 
import os
import csv


Case_Study=[]
graph_to_plot=[]
Selected_dir = os. getcwd()

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 700)

        # =======Central widget + Principal layout =======
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.central_layout = QtWidgets.QVBoxLayout(self.centralwidget)

        # ======= Tabs =======
        self.tabWidget = QtWidgets.QTabWidget()
        self.central_layout.addWidget(self.tabWidget)

        # =====================  Tab Files  =====================
        self.Files = QtWidgets.QWidget()
        files_layout = QtWidgets.QVBoxLayout(self.Files)

        # --- field for files ---
        file_grid = QtWidgets.QGridLayout()
        file_grid.addWidget(QtWidgets.QLabel("Roughness file :"), 0, 0)
        self.lineEdit_5 = QtWidgets.QLineEdit()
        file_grid.addWidget(self.lineEdit_5, 0, 1)
        self.toolButton_5 = QtWidgets.QToolButton()
        self.toolButton_5.setText("...")
        file_grid.addWidget(self.toolButton_5, 0, 2)

        file_grid.addWidget(QtWidgets.QLabel("Parameters :"), 1, 0)
        self.lineEdit = QtWidgets.QLineEdit()
        file_grid.addWidget(self.lineEdit, 1, 1)
        self.toolButton = QtWidgets.QToolButton()
        self.toolButton.setText("...")
        file_grid.addWidget(self.toolButton, 1, 2)

        file_grid.addWidget(QtWidgets.QLabel("Rail Accelerance  :"), 2, 0)
        self.lineEdit_12 = QtWidgets.QLineEdit()
        file_grid.addWidget(self.lineEdit_12, 2, 1)
        self.toolButton_6 = QtWidgets.QToolButton()
        self.toolButton_6.setText("...")
        file_grid.addWidget(self.toolButton_6, 2, 2)

        file_grid.addWidget(QtWidgets.QLabel("Lateral Wheel Compliance :"), 3, 0)
        self.lineEdit_2 = QtWidgets.QLineEdit()
        file_grid.addWidget(self.lineEdit_2, 3, 1)
        self.toolButton_2 = QtWidgets.QToolButton()
        self.toolButton_2.setText("...")
        file_grid.addWidget(self.toolButton_2, 3, 2)

        file_grid.addWidget(QtWidgets.QLabel("Vertical Wheel Compliance :"), 4, 0)
        self.lineEdit_14 = QtWidgets.QLineEdit()
        file_grid.addWidget(self.lineEdit_14, 4, 1)
        self.toolButton_8 = QtWidgets.QToolButton()
        self.toolButton_8.setText("...")
        file_grid.addWidget(self.toolButton_8, 4, 2)

        file_grid.addWidget(QtWidgets.QLabel("Lateral Rail Accelerance  :"), 5, 0)
        self.lineEdit_3 = QtWidgets.QLineEdit()
        file_grid.addWidget(self.lineEdit_3, 5, 1)
        self.toolButton_3 = QtWidgets.QToolButton()
        self.toolButton_3.setText("...")
        file_grid.addWidget(self.toolButton_3, 5, 2)

        file_grid.addWidget(QtWidgets.QLabel("Vertical Rail Accelerance  :"), 6, 0)
        self.lineEdit_4 = QtWidgets.QLineEdit()
        file_grid.addWidget(self.lineEdit_4, 6, 1)
        self.toolButton_4 = QtWidgets.QToolButton()
        self.toolButton_4.setText("...")
        file_grid.addWidget(self.toolButton_4, 6, 2)

        file_grid.addWidget(QtWidgets.QLabel("Save to  :"), 7, 0)
        self.lineEdit_13 = QtWidgets.QLineEdit()
        file_grid.addWidget(self.lineEdit_13, 7, 1)
        self.toolButton_7 = QtWidgets.QToolButton()
        self.toolButton_7.setText("...")
        file_grid.addWidget(self.toolButton_7, 7, 2)

        files_layout.addLayout(file_grid)

        # --- parameters ---
        param_grid = QtWidgets.QGridLayout()
        self.checkBox = QtWidgets.QCheckBox("Enable extra options")
        param_grid.addWidget(self.checkBox, 0, 0, 1, 3)

        param_grid.addWidget(QtWidgets.QLabel("Speed [km/h] :"), 1, 0)
        self.lineEdit_6 = QtWidgets.QLineEdit()
        param_grid.addWidget(self.lineEdit_6, 1, 1)

        param_grid.addWidget(QtWidgets.QLabel("Load [kN] :"), 1, 2)
        self.lineEdit_7 = QtWidgets.QLineEdit()
        param_grid.addWidget(self.lineEdit_7, 1, 3)

        param_grid.addWidget(QtWidgets.QLabel("Rw [mm] :"), 2, 0)
        self.lineEdit_8 = QtWidgets.QLineEdit()
        param_grid.addWidget(self.lineEdit_8, 2, 1)

        param_grid.addWidget(QtWidgets.QLabel("Rwt [mm] :"), 2, 2)
        self.lineEdit_9 = QtWidgets.QLineEdit()
        param_grid.addWidget(self.lineEdit_9, 2, 3)

        param_grid.addWidget(QtWidgets.QLabel("Rrt [mm] :"), 2, 4)
        self.lineEdit_10 = QtWidgets.QLineEdit()
        param_grid.addWidget(self.lineEdit_10, 2, 5)

        files_layout.addLayout(param_grid)

        # --- ComboBox ---
        combo_grid = QtWidgets.QGridLayout()
        combo_grid.addWidget(QtWidgets.QLabel("Output :"), 0, 0)
        combo_grid.addWidget(QtWidgets.QLabel("Unit :"), 0, 1)
        combo_grid.addWidget(QtWidgets.QLabel("Observation point :"), 0, 2)
        files_layout.addLayout(combo_grid)

        combo_layout = QtWidgets.QHBoxLayout()
        self.comboBox_2 = QtWidgets.QComboBox()
        self.comboBox_2.addItems(["", "", "","", "",""])
        combo_layout.addWidget(self.comboBox_2)

        self.comboBox_3 = QtWidgets.QComboBox()
        self.comboBox_3.addItem("")
        combo_layout.addWidget(self.comboBox_3)

        self.comboBox_5 = QtWidgets.QComboBox()
        self.comboBox_5.addItem("")
        combo_layout.addWidget(self.comboBox_5)

        files_layout.addLayout(combo_layout)
        self.tabWidget.addTab(self.Files, "Files")
        
        # ---   list + boutuns ---
        list_button_layout = QtWidgets.QHBoxLayout()
        self.listView = QtWidgets.QListView()
        list_button_layout.addWidget(self.listView)

        btn_layout = QtWidgets.QVBoxLayout()
        self.pushButton = QtWidgets.QPushButton("Add File")
        self.pushButton_2 = QtWidgets.QPushButton("Remove File")
        self.pushButton_3 = QtWidgets.QPushButton("Run")
        btn_layout.addWidget(self.pushButton)
        btn_layout.addWidget(self.pushButton_2)
        btn_layout.addWidget(self.pushButton_3)
        btn_layout.addStretch()

        list_button_layout.addLayout(btn_layout)
        files_layout.addLayout(list_button_layout)

        # ===================== Tab 2 =====================
        self.tab_2 = QtWidgets.QWidget()
        tab2_layout = QtWidgets.QVBoxLayout(self.tab_2)

        title_layout = QtWidgets.QHBoxLayout()
        title_layout.addWidget(QtWidgets.QLabel("Title:"))
        self.lineEdit_11 = QtWidgets.QLineEdit()
        title_layout.addWidget(self.lineEdit_11)
        tab2_layout.addLayout(title_layout)

        self.listView_2 = QtWidgets.QListView()
        tab2_layout.addWidget(self.listView_2)

        btn_bottom_layout = QtWidgets.QHBoxLayout()
        self.pushButton_5 = QtWidgets.QPushButton("Add File")
        self.pushButton_6 = QtWidgets.QPushButton("Remove File")
        btn_bottom_layout.addWidget(self.pushButton_5)
        btn_bottom_layout.addWidget(self.pushButton_6)
        tab2_layout.addLayout(btn_bottom_layout)

        self.comboChek = Check.CheckableComboBox()
        tab2_layout.addWidget(self.comboChek)

        combo2_layout = QtWidgets.QHBoxLayout()
        combo2_layout.addWidget(QtWidgets.QLabel("Y axis : "))
        self.comboBox = QtWidgets.QComboBox()
        self.comboBox.addItems(["Yes", "No"])
        combo2_layout.addWidget(self.comboBox)

        combo2_layout.addWidget(QtWidgets.QLabel("X axis : "))
        self.comboBox_4 = QtWidgets.QComboBox()
        self.comboBox_4.addItems(["On", "Off"])
        combo2_layout.addWidget(self.comboBox_4)

        self.pushButton_4 = QtWidgets.QPushButton("Apply")
        combo2_layout.addWidget(self.pushButton_4)
        tab2_layout.addLayout(combo2_layout)

        self.tabWidget.addTab(self.tab_2, "Tab 2")


        


        # End
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "postprocess"))
        self.lineEdit_6.setText(_translate("MainWindow", "100"))
        self.lineEdit_7.setText(_translate("MainWindow", "54"))
        self.lineEdit_8.setText(_translate("MainWindow", "475"))
        self.lineEdit_9.setText(_translate("MainWindow", "300"))
        self.lineEdit_10.setText(_translate("MainWindow", "300"))
        self.checkBox.setText(_translate("MainWindow", "Merge results"))
        self.toolButton_5.setText(_translate("MainWindow", "..."))

        self.lineEdit.setToolTip('The file looking for is the .json file used for the simulation. Be carrefour,\nthe result files don\'t be moved from the result folder indicate in the .json file')
        self.lineEdit_2.setToolTip('This field is used to implement the lateral wheel compliance express in m/N (.txt). ')
        self.lineEdit_14.setToolTip('This field is used to implement the vertical wheel compliance express in m/s/N (.txt). ')
        self.lineEdit_3.setToolTip('This field is used to implement the lateral accelerance  of the rail (.txt).\nThe file sought is the result of the harmonic simulation\n in the case where the load is applied laterally in the rail at the same point as the study case.')
        self.lineEdit_4.setToolTip('This field is used to implement the lateral accelerance  of the rail (.txt).\nThe file sought is the result of the harmonic simulation\n in the case where the load is applied vertically in the rail at the same point as the study case.')
        self.lineEdit_5.setToolTip('This field is used to implement a roughness file (.csv).\nIf not specified, the value will be expressed in units of m')
        self.lineEdit_12.setToolTip('This field requires the FRF.txt results obtained from the case study. This file is useful for exporting acceleration and mobility. By default, the path used is the one found in the .json file.')
        self.lineEdit_13.setToolTip('Folder in which results are saved')
        self.lineEdit_6.setToolTip('Train speed')
        self.lineEdit_7.setToolTip('wheel load')
        self.lineEdit_8.setToolTip('wheel radius')
        self.lineEdit_9.setToolTip('Transversal wheel radius')
        self.lineEdit_10.setToolTip('Transversal rail radus')
        self.checkBox.setToolTip('By checking this box, all the results you require will be merged into a single file')

        self.comboBox_2.setItemText(0, _translate("MainWindow", "Contact Force"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Vertical Rail Contact Force"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Lateral Rail Contact Force"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "Rail_Accelerance "))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "Rail_Mobility"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "Wheel_Mobility"))
        # self.comboBox_2.setItemText(5, _translate("MainWindow", "Total Soud Pressure Level"))
        # self.comboBox_2.setItemText(6, _translate("MainWindow", "Sound Pressure Level at the point P1"))
        # self.comboBox_2.setItemText(7, _translate("MainWindow", "Sound Pressure Level at the point P2"))
        # self.comboBox_2.setItemText(8, _translate("MainWindow", "Sound Pressure Level at the point P3"))


        self.comboBox_3.setItemText(0, _translate("MainWindow", "N"))

        self.comboBox.setItemText(0, _translate("MainWindow", "Linear"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Log"))

        self.comboBox_4.setItemText(0, _translate("MainWindow", "Linear"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "Log"))

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Files), _translate("MainWindow", "Export results"))
        self.pushButton_4.setText(_translate("MainWindow", "Plot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Plot"))

    def Rougness_search(self):
        filename = filedialog.askopenfilename(filetypes =[('csv files', '*.csv')], initialdir = Selected_dir)
        self.lineEdit_5.setText(filename)
        return filename
    
    def Wheel_Lat_search(self):
        filename = filedialog.askopenfilename(filetypes =[('txt files', '*.txt')])
        self.lineEdit_2.setText(filename)
        return filename
    
    def Wheel_Vert_search(self):
        filename = filedialog.askopenfilename(filetypes =[('txt files', '*.txt')])
        self.lineEdit_14.setText(filename)
        return filename
    
    def Rail_Lat_search(self):
        filename = filedialog.askopenfilename(filetypes =[('txt files', '*.txt')])
        self.lineEdit_3.setText(filename)
        return filename
    
    def Rail_search(self):
        filename = filedialog.askopenfilename(filetypes =[('txt files', '*.txt')])
        self.lineEdit_12.setText(filename)
        return filename

    def Save_search(self):
        filename = filedialog.askdirectory()
        self.lineEdit_13.setText(filename)
        return filename
    
    def Rail_Vert_search(self):
        filename = filedialog.askopenfilename(filetypes =[('txt files', '*.txt')])
        self.lineEdit_4.setText(filename)

        return filename
    
    def para_file(self):
        filename = filedialog.askopenfilename(filetypes =[('json files', '*.json')])
        self.lineEdit.setText(filename)
        self.comboBox_5.clear()
        try:
            with open(filename, 'r') as f:
                txt = f.read()
            f.close()
            parameters = json.loads(txt)
            points_list= parameters["nodesFRF"]
            for k in range(len(points_list)):
                self.comboBox_5.addItem(points_list[k])

        except:
            print('.json not found')
        
        try:
            if(self.lineEdit_12.text() == ''):
                self.lineEdit_12.setText(os.path.join(parameters['simuParentFolder'],parameters['name'],'Outputs','FRF.txt'))
            
            if(self.lineEdit_13.text() == ''):
                self.lineEdit_13.setText(os.path.join(parameters['simuParentFolder'],parameters['name'],'Outputs'))
        except:
            pass

        


            

        return filename

    def changeUnit(self):
        value = self.comboBox_2.currentText()
        if(value == 'Contact Force' or value == 'Vertical Rail Contact Force' or value == 'Lateral Rail Contact Force'):
            self.comboBox_3.clear()
            self.comboBox_3.addItems(["N"])
        if(value == "Total Soud Pressure Level" or value == "Sound Pressure Level at the point P1" or value == "Sound Pressure Level at the point P2" or value == "Sound Pressure Level at the point P3"):
            self.comboBox_3.clear()
            self.comboBox_3.addItems(["Pa",  "DB", "DBA"])
        if(value == "Rail_Accelerance "):
            self.comboBox_3.clear()
            self.comboBox_3.addItems(["g/N","m/s^2/N"])
        if(value == "Rail_Mobility" or value == "Wheel_Mobility"):
            self.comboBox_3.clear()
            self.comboBox_3.addItems(["m/sN"])
        
        return
    
    def Add_to_list(self):
        Case_Study.append([self.comboBox_2.currentText(),self.comboBox_3.currentText()])
        model.appendRow(QtGui.QStandardItem(self.comboBox_2.currentText()+ ' - ' + self.comboBox_3.currentText()))
        return

    def Add_to_snd_list(self):
        quantities=[]
        filename = filedialog.askopenfilename(filetypes =[('csv files', '*.csv')])
        graph_to_plot.append(filename)
        model2.appendRow(QtGui.QStandardItem(filename))

        try :
            for k in range(len(graph_to_plot)):
                with open(graph_to_plot[k], 'r', encoding='utf-8') as file:
                    ligne = file.readline()
                    quantities=quantities+ligne.split(',')[1:]
                    tmp_string=quantities.pop()
                    quantities.append(tmp_string[:len(tmp_string)-1])
            
            self.comboChek.add_items(quantities)
        except:
            print('No match')
            
        return
    
    def Rmv_to_list(self):#
        try:
            A=self.listView.selectedIndexes()
            item=self.listView.model().itemFromIndex(A[0])
            for k in range(len(Case_Study)):
                if(Case_Study[k][0] + ' - ' +Case_Study[k][1]==item.text()):
                    rmv_index=k

            model.removeRow(rmv_index)
            Case_Study.pop(rmv_index)
        except:
            print('A problem has occurred. No items have been selected.')
        return 
    
    def Rmv_to_snd_list(self):#
        try:
            quantities=[]
            A=self.listView_2.selectedIndexes()
            item=self.listView_2.model().itemFromIndex(A[0])
            for k in range(len(graph_to_plot)):
                if(graph_to_plot[k] == item.text()):
                    rmv_index_2=k

            model2.removeRow(rmv_index_2)
            graph_to_plot.pop(rmv_index_2)
        except:
            print('A problem has occurred. No items have been selected.')

        try :
            for k in range(len(graph_to_plot)):
                with open(graph_to_plot[k], 'r', encoding='utf-8') as file:
                    ligne = file.readline()
                    quantities=quantities+ligne.split(',')[1:]
                    tmp_string=quantities.pop()
                    quantities.append(tmp_string[:len(tmp_string)-1])
            
            self.comboChek.add_items(quantities)
        except:
            print('No match')

        return 
    
    def plot_graph(self):
        try:            
            grandeurs = []
            All =[]
            

            for file in graph_to_plot:
                Table = []
                with open(file, 'r', newline='', encoding='utf-8') as f:
                    lecteur = csv.reader(f, delimiter=',')
                    
                    header = next(lecteur)
                    header_selected=[header[0]]
                    for k in range(len(header)):
                        if(header[k] in self.comboChek.checked_items()):
                            header_selected.append(header[k])

                    for row in lecteur:
                        Liste_Temp = []
                        for q in range (len(header)):
                            if(q==0 or (header[q] in self.comboChek.checked_items())):
                                Liste_Temp.append(float(row[q]))
                        Table.append(Liste_Temp)
                    Table_Matrice = np.array(Table)

                    for p in range(1,len(header_selected)):
                        p1=header_selected[p].find('[')
                        p2=header_selected[p].find(']')
                        unit=header_selected[p][p1:p2+1]
                        if (not (unit in grandeurs)):
                            grandeurs.append(unit)
                            All.append([[Table_Matrice[:,p],Table_Matrice[:,0],header_selected[p]]])
                        else:
                            All[grandeurs.index(unit)].append([Table_Matrice[:,p],Table_Matrice[:,0],header_selected[p]])
                        
            for k in range(0,len(grandeurs)):
                print(grandeurs)
                plt.figure()
                plt.title(self.lineEdit_11.text())
                lgd=[]
                for p in range(len(All[k])):
                    plt.plot(All[k][p][1],All[k][p][0])
                    lgd.append(All[k][p][2])
                
                plt.legend(lgd)
                if (grandeurs[k]!='[rad]'):
                    if(self.comboBox_4.currentText()=='Log'):
                        plt.xscale('log')
                    if(self.comboBox.currentText()=='Log'):
                        plt.yscale('log')
                
                plt.xlabel('Frequency [Hz]')      
            plt.show()

        except Exception as e:
             print(e)
             msgBox = QtWidgets.QMessageBox()
             msgBox.setText("unable to plot values ")
             msgBox.exec()
    
    
    def run(self) :
        try:
            coef_conv = 1
            pathFile = self.lineEdit.text()
            get_more_parameters = True

            if(pathFile!=""):
                str_temps=self.comboBox_5.currentText()
                GrNodes = str_temps[0:len(str_temps)-2]
                if os.path.exists(pathFile) == False:
                    print('File parameters.json not found for ' + pathFile + '.')
                    parameters = None
                    paramFile = None
                else:
                    with open(pathFile, 'r') as f:
                        txt = f.read()
                    f.close()
                    parameters = json.loads(txt)
                    paramFile = pathFile

                try:
                    #path = os.path.join(parameters['simuParentFolder'],parameters['name'],'Outputs','FRF.txt')    
                    #path = parameters['simuParentFolder'] + '\\' + parameters['name'] + '\\' + 'FRF.txt' #ToChange
                    path = self.lineEdit_12.text()
                    GrNodes= 'E' + str(parameters['slpForce']) + '_' + GrNodes

                        
                    ### Extraction des données des mobilitées du cas d'études
                        
                        
                    freq, Ly_amp, Ly_phase, Lz_amp, Lz_phase = [], [], [], [], []

                    with open(path) as f :
                        Extract_FRF = f.readlines()

                    Tabl = Extract_FRF[0].split('	')

                    for k in range(len(Tabl)):
                        if(Tabl[k]==GrNodes+'_Y'+' [g/N]'):
                            indiceY=k
                        if(Tabl[k]==GrNodes+'_Z'+' [g/N]'):
                            indiceZ=k
                    for p in range(1,len(Extract_FRF)):
                        temp = Extract_FRF[p].split('	')
                        freq.append(float(temp[0]))
                        Ly_amp.append(float(temp[indiceY]))
                        Ly_phase.append(float(temp[indiceY+1]))
                        Lz_amp.append(float(temp[indiceZ]))
                        Lz_phase.append(float(temp[indiceZ+1]))
                except:
                    get_more_parameters = False
                # else:
                #     get_more_parameters = False
    
            Result = []
            
            try:
                # Rail Definition
                Rail=Solid(1,1,'rail')
                Rail.setRail_mobility(self.lineEdit_3.text(), self.lineEdit_4.text(),GrNodes)
            except:
                print('No rail definition')

            # Wheel Definition

            Wheel=Solid(1,1,'roue')
            try:
                Wx_mobility, Wz_mobility = Wheel.setWheel_mobility([self.lineEdit_2.text(),self.lineEdit_14.text()])
            except:
                try:
                    Wheel.freq=freq
                except:
                    print('No wheel definition')

            try:
                w_start,w_end,_,_= Wheel.Cut_Mobility(Rail)
            except:
                w_start,w_end = 0,-1
            
            try:
                Fy_amp,Fy_phase,Fz_amp,Fz_phase,H,WaveNumber,echec = Contact_Load(Rail,Wheel,self.lineEdit_5.text(),parameters,float(self.lineEdit_6.text()),float(self.lineEdit_8.text()),float(self.lineEdit_9.text()),float(self.lineEdit_10.text()),float(self.lineEdit_7.text()))
                if echec :
                    msgBox = QtWidgets.QMessageBox()
                    msgBox.setText("The roughness file could not be find so the result will be express per unit of m")
                    msgBox.exec()

                Fn=(np.array(Fy_amp)**2 + np.array(Fz_amp)**2)**(1/2)
            
            except Exception as e:
                print('Any contact force has been computed')
                print(f"Unexpected {e}, {type(e)}")
                
            for k in range(len(Case_Study)):
                if(k==0 or not self.checkBox.checkState()):
                    Result.append(Wheel.freq)
                    headers = ['Frequency [Hz]']

                headerToAdd = ''
                if(Case_Study[k][0] == "Contact Force"):
                    Result.append(Fn)
                    

                if(Case_Study[k][0] == "Vertical Rail Contact Force"):
                    Result.append(Fz_amp)
                    Result.append(Fz_phase)
                    headerToAdd = ', Vertical Rail Contact Force_phase [rad]'

                if(Case_Study[k][0] == "Lateral Rail Contact Force"):
                    Result.append(Fy_amp)
                    Result.append(Fy_phase)
                    headerToAdd = ', Lateral Rail Contact Force_phase [rad]'

                if(Case_Study[k][0] == "Wheel_Mobility"):
                    Result.append(Wx_mobility[0][w_start:w_end])
                    Result.append(Wx_mobility[1][w_start:w_end])
                    Result.append(Wx_mobility[2][w_start:w_end])
                    Result.append(Wx_mobility[3][w_start:w_end])
                    Result.append(Wz_mobility[0][w_start:w_end])
                    Result.append(Wz_mobility[1][w_start:w_end])
                    Result.append(Wz_mobility[2][w_start:w_end])
                    Result.append(Wz_mobility[3][w_start:w_end])
                    headerToAdd = '[X], Wheel_Mobility [rad] [X], Wheel_Mobility [m/sN] [XZ], Wheel_Mobility [rad] [XZ], Wheel_Mobility [m/sN] [ZX], Wheel_Mobility [rad] [ZX], Wheel_Mobility [m/sN] [Z], Wheel_Mobility [rad] [Z]'

                if(get_more_parameters):    
                    if(Case_Study[k][0] == "Rail_Accelerance "):
                        if(Case_Study[k][1]=="m/s^2/N"):
                            coef_conv=9.81
                        Acc=coef_conv*np.array(Ly_amp)*np.exp(1j*np.array(Ly_phase)/180*np.pi)
                        Result.append(list(np.interp(np.array(Wheel.freq),freq,abs(Acc))))
                        interp=PchipInterpolator(freq, np.angle(Acc))
                        phase_interpolate=interp(Wheel.freq)
                        Result.append(savgol_filter(phase_interpolate, window_length=11, polyorder=2))

                        Acc=np.array(Lz_amp)*np.exp(1j*np.array(Lz_phase)/180*np.pi)
                        Result.append(list(np.interp(np.array(Wheel.freq),freq,abs(Acc))))
                        interp=PchipInterpolator(freq, np.angle(Acc))
                        phase_interpolate=interp(Wheel.freq)
                        Result.append(np.interp(np.array(Wheel.freq),freq,np.angle(Acc)))

                        headerToAdd = ' [Y], Rail_Accelerance _phase [rad] [Y], Rail_Accelerance  ['+ Case_Study[k][1] + ']  [Z], Rail_Accelerance _phase [rad] [Z]'

                    if(Case_Study[k][0] == "Rail_Mobility"):
                        velocity=(np.array(Ly_amp)*9.81/(2j*np.pi*np.array(freq)))*np.exp(1j*np.array(Ly_phase)/180*np.pi)
                        Result.append(list(np.interp(np.array(Wheel.freq),freq,abs(velocity))))
                        interp=PchipInterpolator(freq, np.angle(velocity))
                        phase_interpolate=interp(Wheel.freq)
                        Result.append(savgol_filter(phase_interpolate, window_length=11, polyorder=2))

                        velocity=(np.array(Lz_amp)*9.81/(2j*np.pi*np.array(freq)))*np.exp(1j*np.array(Lz_phase)/180*np.pi)
                        Result.append(list(np.interp(np.array(Wheel.freq),freq,abs(velocity))))
                        interp=PchipInterpolator(freq, np.angle(velocity))
                        phase_interpolate=interp(Wheel.freq)
                        Result.append(np.interp(np.array(Wheel.freq),freq,np.angle(velocity)))

                        headerToAdd = ' [Y], Rail_Mobility_phase [rad] [Y], Rail_Mobility [m/sN] [Z], Rail_Mobility_phase [rad] [Z]'
                    
                    if(Case_Study[k][0] == "Sound Pressure Level at the point P1"):
                        ResultAccoust = SimulationResults(parameters['simuParentFolder'])
                        FRF_pressTot1 = ResultAccoust.FRF_pressTot1*Fn
                        FRF_pressTot2 = ResultAccoust.FRF_pressTot2*Fn
                        FRF_pressTot3 = ResultAccoust.FRF_pressTot3*Fn
                        
                        if(Case_Study[k][1] == 'DB'):
                            Result.append(list(20*np.log10(FRF_pressTot1/ResultAccoust.p_ref)))
                        if(Case_Study[k][1] == 'DBA'):
                            Result.append(ResultAccoust.apply_A_weighting_linear(ResultAccoust.frequency, FRF_pressTot1))
                        if(Case_Study[k][1] == 'Pa'):
                            Result.append(FRF_pressTot1)

                    if(Case_Study[k][0] == "Sound Pressure Level at the point P2"):
                        ResultAccoust = SimulationResults(parameters['simuParentFolder'])
                        FRF_pressTot1 = ResultAccoust.FRF_pressTot1*Fn
                        FRF_pressTot2 = ResultAccoust.FRF_pressTot2*Fn
                        FRF_pressTot3 = ResultAccoust.FRF_pressTot3*Fn

                        if(Case_Study[k][1] == 'DB'):
                            Result.append(20*np.log10(FRF_pressTot2/ResultAccoust.p_ref))
                        if(Case_Study[k][1] == 'DBA'):
                            Result.append(ResultAccoust.apply_A_weighting_linear(ResultAccoust.frequency, FRF_pressTot2))
                        if(Case_Study[k][1] == 'Pa'):
                            Result.append(FRF_pressTot2)
                    
                    if(Case_Study[k][0] == "Sound Pressure Level at the point P3"):
                        ResultAccoust = SimulationResults(parameters['simuParentFolder'])
                        FRF_pressTot1 = ResultAccoust.FRF_pressTot1*Fn
                        FRF_pressTot2 = ResultAccoust.FRF_pressTot2*Fn
                        FRF_pressTot3 = ResultAccoust.FRF_pressTot3*Fn

                        if(Case_Study[k][1] == 'DB'):
                            Result.append(20*np.log10(FRF_pressTot3/ResultAccoust.p_ref))
                        if(Case_Study[k][1] == 'DBA'):
                            Result.append(ResultAccoust.apply_A_weighting_linear(ResultAccoust.frequency, FRF_pressTot3))
                        if(Case_Study[k][1] == 'Pa'):
                            Result.append(FRF_pressTot3)
                    
                    if(Case_Study[k][0] == "Total Soud Pressure Level"):
                        ResultAccoust = SimulationResults(parameters['simuParentFolder'])
                        FRF_pressTot1 = ResultAccoust.FRF_pressTot1*Fn
                        FRF_pressTot2 = ResultAccoust.FRF_pressTot2*Fn
                        FRF_pressTot3 = ResultAccoust.FRF_pressTot3*Fn

                        FRF_pressTot = []
                        for i in range(len(FRF_pressTot1)):
                            FRF_pressTot.append(ResultAccoust.integrate_spatial(ResultAccoust.FRF_pressTot1[i]*Fn[i], ResultAccoust.FRF_pressTot2[i]*Fn[i],ResultAccoust.FRF_pressTot3[i]*Fn[i])) # Moyenne des pressions
                        if(Case_Study[k][1] == 'DB'):
                            Result.append(20*np.log10(np.array(FRF_pressTot)/ResultAccoust.p_ref))
                        if(Case_Study[k][1] == 'DBA'):
                            Result.append(ResultAccoust.apply_A_weighting_linear(ResultAccoust.frequency, FRF_pressTot))
                        if(Case_Study[k][1] == 'Pa'):
                            Result.append(FRF_pressTot)


                if(len(headerToAdd.split(','))>1):
                    splitHeaderToAdd = headerToAdd.split(',')
                    headers.append(Case_Study[k][0] + ' [' + Case_Study[k][1] + ']')
                    headers[-1] = headers[-1] + splitHeaderToAdd.pop(0)
                    headers = headers + splitHeaderToAdd
                else:
                    headers.append(Case_Study[k][0] + ' [' + Case_Study[k][1] + ']' + headerToAdd) 
                
                if(not self.checkBox.checkState()):
                    nextStep=True
                    if((Case_Study[k][0]== 'Rail_Accelerance ' or Case_Study[k][0]== 'Rail_Mobility' or Case_Study[k][0]== 'Wheel_Mobility')):
                        path_to_add= Case_Study[k][0] + '.csv'
                        
                        if(not get_more_parameters and not(Case_Study[k][0]== 'Wheel_Mobility')):
                            msgBox = QtWidgets.QMessageBox()
                            msgBox.setText("impossible to perform the calculation to obtain the file : " + Case_Study[k][0] + ", because it requires the presence of the rail accelerance file (FRF.txt) associated with the case study.\nPlease check the information entered.")
                            msgBox.exec()
                            nextStep=False
                            
                    else:
                        path_to_add=Case_Study[k][0] + '_' + Case_Study[k][1]+ '.csv'
                            
                    if(nextStep):
                        try:
                            with open(os.path.join(self.lineEdit_13.text(),path_to_add), mode="w", newline="", encoding="utf-8") as file:
                                writer = csv.writer(file, delimiter=',')
                                writer.writerow(headers)      # Write the header
                                writer.writerows(np.array(Result).T)
                        except:
                            msgBox = QtWidgets.QMessageBox()
                            msgBox.setText("A problem occurred while saving the files. The path specified for exporting may be incorrect.")
                            msgBox.exec()
                    
                    #headers.pop()
                    Result = []
                    
                
                
            if(self.checkBox.checkState()):
                try:
                    with open(os.path.join(self.lineEdit_13.text(),'result.csv'), mode="w", newline="", encoding="utf-8") as file:
                        writer = csv.writer(file, delimiter=',')
                        writer.writerow(headers)      # Write the header
                        writer.writerows(np.array(Result).T)
                except:
                    msgBox = QtWidgets.QMessageBox()
                    msgBox.setText("A problem occurred while saving the files. The path specified for exporting may be incorrect.")
                    msgBox.exec() 

        except Exception as e :
            print(e)

        return   
    

if __name__ == '__main__':
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(window)
    ui.toolButton.clicked.connect(ui.para_file)
    ui.toolButton_2.clicked.connect(ui.Wheel_Lat_search)
    ui.toolButton_8.clicked.connect(ui.Wheel_Vert_search)
    ui.toolButton_3.clicked.connect(ui.Rail_Lat_search)
    ui.toolButton_4.clicked.connect(ui.Rail_Vert_search)
    ui.toolButton_5.clicked.connect(ui.Rougness_search)
    ui.toolButton_6.clicked.connect(ui.Rail_search)
    ui.toolButton_7.clicked.connect(ui.Save_search)
    

    model = QtGui.QStandardItemModel()
    ui.listView.setModel(model)
    try:
        ui.pushButton.clicked.connect(ui.Add_to_list)
        ui.pushButton_2.clicked.connect(ui.Rmv_to_list)
        ui.pushButton_3.clicked.connect(ui.run)
    except:
        pass

    

    model2 = QtGui.QStandardItemModel()
    ui.listView_2.setModel(model2)

    try:
        ui.pushButton_5.clicked.connect(ui.Add_to_snd_list)
        ui.pushButton_6.clicked.connect(ui.Rmv_to_snd_list)

        ui.pushButton_4.clicked.connect(ui.plot_graph)
        ui.comboBox_2.activated.connect(ui.changeUnit)
    except:
        pass


    window.show()
    sys.exit(app.exec_())